Matter Temperature Sensor
adafruit/circuitmatter pull request #17
Opened 2024-10-17 15:00 UTC by lboue

Add Matter Temperature Sensor:
- Cluster
- Device type

2024-10-17 16:45 UTC, tannewt requested changes
Thanks for doing this! Very excited to see it.

I've got a few small suggestions to better match the specs.

2024-10-17 16:45 UTC, tannewt commented on circuitmatter/clusters/general/temperature_measurement.py
Please move this to `clusters/measurement`. I want to mirror the chapter structure of the application clusters spec.

2024-10-17 16:45 UTC, tannewt commented on circuitmatter/clusters/general/temperature_measurement.py
> +    CLUSTER_ID = 0x0402
```suggestion
    CLUSTER_ID = 0x0402
    REVISION = 4
```

2024-10-17 16:45 UTC, tannewt commented on circuitmatter/device_types/measurement/temperature_sensor.py
Let's do `device_types/sensor` to match "Chapter 7. Sensor Device Type".

2024-10-18 05:41 UTC, lboue commented on circuitmatter/clusters/general/temperature_measurement.py
Good idea

2024-10-19 09:33 UTC, closed without merging

2024-10-19 09:33 UTC, lboue commented
Closing this in favor of #21.